[package]
name = "scirs2-autograd"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["SciRS2 Team"]
license = "Apache-2.0"
description = "Automatic differentiation module for SciRS2"
repository = "https://github.com/cool-japan/scirs"
keywords = ["autograd", "machine-learning", "scientific", "ai", "ml"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
ndarray = { version = "0.16.1", features = ["serde"] }
num-traits = "0.2.19"
rayon = "1.10.0"
rand = "0.9.0"
rand_core = "0.9.3"
rand_distr = "0.5.1"
approx = "0.5.1"
thiserror = "2.0.12"
num-complex = "0.4.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19.0"
smallvec = "1.2.0"
uuid = { version = "1.3.0", features = ["v4"] }
rustc-hash = "1.1.0"
libc = "0.2"
matrixmultiply = "0.3.2"
num = "0.4.0"
special = "0.10.2"
scirs2-core = { version = "0.1.0-alpha.1", path = "../scirs2-core" }
# Remove dependency on scirs2-linalg to avoid circular dependency

# BLAS dependencies - feature-gated
blas-src = { version = "0.8", default-features = false, optional = true }
intel-mkl-src = { version = "0.8.1", default-features = false, optional = true }
cblas-sys = { version = "0.1.4", default-features = false, optional = true }

[features]
default = []
blas = []
intel-mkl = ["intel-mkl-src", "cblas-sys"]
accelerate = ["blas-src/accelerate", "cblas-sys"]
openblas = ["blas-src/openblas", "cblas-sys"]
mkl = ["intel-mkl-src", "cblas-sys"]

[[example]]
name = "basic_autograd"
path = "examples/basic_autograd.rs"

[lib]
doctest = false