[package]
name = "scirs2-linalg"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["SciRS2 Team"]
description = "Linear algebra module for SciRS2"
license = "Apache-2.0"
repository = "https://github.com/cool-japan/scirs"
keywords = ["linear-algebra", "matrix", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { path = "../scirs2-core", version = "0.1.0-alpha.1", features = ["linalg", "openblas", "parallel", "simd"] }
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
num-traits = "0.2.19"
num-complex = "0.4.6"
thiserror = "2.0.12"
nalgebra = "0.33.2"
rand = "0.9.0"
rand_distr = "0.5.1"
rand_chacha = "0.9.0"
ndarray-rand = "0.14.0"
approx = "0.5.1"
wide = "0.7.32"
rayon = "1.10.0"
scirs2-autograd = { path = "../scirs2-autograd", version = "0.1.0-alpha.1", optional = true }

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"

[features]
default = ["openblas", "simd"]
netlib = ["scirs2-core/netlib"]
openblas = ["scirs2-core/openblas"]
intel-mkl = ["scirs2-core/intel-mkl"]
tensor_contraction = [] # Optional tensor contraction functionality
simd = ["scirs2-core/simd"] # SIMD-accelerated operations
autograd = ["dep:scirs2-autograd"] # Automatic differentiation support
parallel = ["scirs2-core/parallel"] # Parallel processing support

[[bench]]
name = "linalg_bench"
harness = false
path = "benches/linalg_bench.rs"

[[bench]]
name = "simd_bench"
harness = false
path = "benches/simd_bench.rs"

