name: SciRS2 CI

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2 

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Install system libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential libopenblas-dev \
              pkg-config libfreetype6-dev libfontconfig1-dev

      - name: Run tests
        run: |
          cargo nextest run --workspace \
                            --test-threads=1 --no-fail-fast